name: CI

on:
  pull_request:
    branches: [ master ]

jobs:
  lint:
    name: RuboCop
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true
      - run: bundle exec rake rubocop

  spec:
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "windows-latest"]
        ruby:
          - "2.5"
          - "2.7"
        puppet:
          - '~> 6.0'
          - '~> 7.0'
    needs: lint
    name: RSpec - ${{ matrix.os }} - Ruby ${{ matrix.ruby }} - Puppet  ${{ matrix.puppet }}
    runs-on: ${{ matrix.os }}
    env:
      COVERAGE: yes
      PUPPET_GEM_VERSION: ${{ matrix.puppet }}
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - run: bundle exec rake test
